### ISSUE TITLE
[Release] Release Checklist for Beta Version 0.0.1

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-web#132]
Front End

- [ ] Build staging version to staging.casperdash.io which configuring to mainnet ENV
- [ ] Testing core features on staging.casperdash.io 
- [ ] After testing on staging, inform to community to replace current web wallet with totally new product 
- [ ] Production release on https://wallet.casperdash.io/
- [ ] After release testing

API/SC

- [ ] Release API if anys
- [ ] Release SC to mainnet
